<?php

namespace Tests\Feature\Modules;

use App\Models\User;
use App\Modules\Channels\Models\ChannelAccount;
use App\Modules\Platform\Models\Workspace;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ChannelAccountManageTest extends TestCase
{
    use RefreshDatabase;

    private function user(string $role): User
    {
        $ws = Workspace::create(['name' => 'W', 'slug' => 'w-'.uniqid(), 'status' => 'ACTIVE']);

        return User::factory()->create(['workspace_id' => $ws->id, 'role' => $role, 'status' => 'ACTIVE']);
    }

    public function test_admin_can_create_facebook_channel(): void
    {
        $admin = $this->user('admin');

        $this->actingAs($admin)
            ->post(route('admin.channels.store'), [
                'provider' => 'FACEBOOK',
                'name' => 'Support Page',
                'credentials' => ['app_secret' => 'sec', 'page_access_token' => 'tok'],
                'webhook_secret' => 'verify-1',
            ])
            ->assertRedirect();

        $account = ChannelAccount::where('provider', 'FACEBOOK')->firstOrFail();
        $this->assertSame('Support Page', $account->name);
        $this->assertSame('DRAFT', $account->status);
        $this->assertSame('verify-1', $account->webhook_secret);
        $this->assertSame('tok', $account->credentials['page_access_token']);
    }

    public function test_webhook_secret_autogenerated_when_blank(): void
    {
        $admin = $this->user('admin');

        $this->actingAs($admin)->post(route('admin.channels.store'), [
            'provider' => 'ZALO_PERSONAL',
            'name' => 'Nick 1',
        ])->assertRedirect();

        $account = ChannelAccount::where('provider', 'ZALO_PERSONAL')->firstOrFail();
        $this->assertNotEmpty($account->webhook_secret);
    }

    public function test_support_agent_cannot_create_channel(): void
    {
        $agent = $this->user('support_agent');

        $this->actingAs($agent)->post(route('admin.channels.store'), [
            'provider' => 'TELEGRAM',
            'name' => 'X',
            'credentials' => ['bot_token' => 'y'],
        ])->assertForbidden();

        $this->assertDatabaseCount('channel_accounts', 0);
    }

    public function test_admin_can_update_channel_status_and_merge_credentials(): void
    {
        $admin = $this->user('admin');
        $account = ChannelAccount::create([
            'workspace_id' => $admin->workspace_id,
            'provider' => 'ZALO_OA',
            'name' => 'OA',
            'status' => 'DRAFT',
            'credentials' => ['app_id' => 'a', 'access_token' => 'old'],
        ]);

        $this->actingAs($admin)->put(route('admin.channels.update', $account), [
            'status' => 'ACTIVE',
            'credentials' => ['access_token' => 'new'],
        ])->assertRedirect();

        $account->refresh();
        $this->assertSame('ACTIVE', $account->status);
        $this->assertSame('new', $account->credentials['access_token']);
        $this->assertSame('a', $account->credentials['app_id']); // merged, not wiped
    }

    public function test_register_webhook_sets_url_for_manual_provider(): void
    {
        $admin = $this->user('admin');
        $account = ChannelAccount::create([
            'workspace_id' => $admin->workspace_id,
            'provider' => 'FACEBOOK',
            'name' => 'FB',
            'status' => 'DRAFT',
            'webhook_secret' => 'v',
        ]);

        $this->actingAs($admin)
            ->post(route('admin.channels.register-webhook', $account))
            ->assertRedirect();

        $account->refresh();
        $this->assertSame('ACTIVE', $account->status);
        $this->assertStringContainsString('/webhooks/facebook/'.$account->id, (string) $account->webhook_url);
    }

    public function test_owner_can_delete_channel_but_admin_cannot(): void
    {
        $admin = $this->user('admin');
        $account = ChannelAccount::create([
            'workspace_id' => $admin->workspace_id,
            'provider' => 'TELEGRAM',
            'name' => 'Del Me',
            'status' => 'ACTIVE',
        ]);

        // admin is forbidden to delete (owner-only)
        $this->actingAs($admin)->delete(route('admin.channels.destroy', $account))->assertForbidden();
        $this->assertDatabaseHas('channel_accounts', ['id' => $account->id]);

        // owner in the same workspace can delete
        $owner = User::factory()->create(['workspace_id' => $admin->workspace_id, 'role' => 'owner', 'status' => 'ACTIVE']);
        $this->actingAs($owner)->delete(route('admin.channels.destroy', $account))->assertRedirect();
        $this->assertDatabaseMissing('channel_accounts', ['id' => $account->id]);
    }
}
