<?php

namespace App\Modules\Crm\Services;

use App\Modules\Crm\Models\Contact;
use App\Modules\Crm\Models\ContactNote;
use App\Modules\Crm\Models\ExternalIdentity;
use App\Modules\Crm\Models\Lead;
use App\Modules\Inbox\Models\Conversation;
use App\Modules\Platform\Models\AuditLog;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Contact merge chokepoint (spec 15 § C5).
 *
 * Strategy:
 *   1. Re-point every FK from $loser → $winner
 *      (external_identities, contact_notes, leads, conversations).
 *      timeline_activities.subject_id is INTENTIONALLY left alone per
 *      spec — timeline rows stay attributed to whoever created them
 *      so the audit trail remains a faithful history.
 *   2. Apply the conflict-resolution policy (see method below).
 *   3. Hard-delete the losers.
 *   4. Write one audit_log row with the merge context.
 *
 * All work runs in a single DB transaction so a partial failure rolls
 * the whole merge back — never a half-merged contact.
 *
 * The merge is destructive: losers vanish, their conversations are
 * silently inherited by the winner. Callers (controller, future bulk
 * merge UI) MUST surface a preview before committing — the conflict
 * preview is generated by preview() below and uses the same policy.
 */
final class ContactMerger
{
    /** Permissive order for status — leftmost wins. */
    private const STATUS_PERMISSIVE = ['ACTIVE', 'ARCHIVED', 'BLOCKED'];

    /**
     * Compute the post-merge snapshot for the winner. Pure / read-only —
     * does NOT touch the database. The UI uses this to show a side-by-
     * side diff before the user confirms.
     *
     * @param  Collection<int, Contact>  $losers  hydrated Contact models
     * @return array<string, mixed> merged-field snapshot for preview
     */
    public function preview(Contact $winner, Collection $losers): array
    {
        $merged = $this->applyPolicy($winner, $losers);

        return [
            'winner_id' => $winner->id,
            'loser_ids' => $losers->pluck('id')->all(),
            'merged_fields' => [
                'full_name' => $merged['full_name'],
                'phone' => $merged['phone'],
                'phone_normalized' => $merged['phone_normalized'],
                'email' => $merged['email'],
                'avatar_url' => $merged['avatar_url'],
                'tags' => $merged['tags'],
                'status' => $merged['status'],
                'owner_id' => $merged['owner_id'],
                'last_inbound_at' => $merged['last_inbound_at'],
                'attributes' => $merged['attributes'],
                'consent_given_at' => $merged['consent_given_at'],
                'consent_text' => $merged['consent_text'],
                'consent_ip' => $merged['consent_ip'],
                'consent_user_agent' => $merged['consent_user_agent'],
                'source_detail' => $merged['source_detail'],
            ],
            'diffs' => $this->diffs($winner, $losers, $merged),
        ];
    }

    /**
     * Apply the merge. Returns the fresh winner.
     *
     * @param  Collection<int, Contact>  $losers
     *
     * @throws RuntimeException on self-merge / cross-workspace / empty loser set
     */
    public function merge(Contact $winner, Collection $losers): Contact
    {
        if ($losers->isEmpty()) {
            throw new RuntimeException('No losers supplied for merge.');
        }

        foreach ($losers as $loser) {
            if ((string) $loser->id === (string) $winner->id) {
                throw new RuntimeException('Cannot merge a contact into itself.');
            }
            if ((string) $loser->workspace_id !== (string) $winner->workspace_id) {
                throw new RuntimeException('Cannot merge contacts across workspaces.');
            }
        }

        // winner.id is the survival target. The unique index on
        // (workspace_id, phone_normalized) and (workspace_id, email) means
        // winner's existing rows naturally defend their values.
        return DB::transaction(function () use ($winner, $losers) {
            $merged = $this->applyPolicy($winner, $losers);

            $diffs = $this->diffs($winner, $losers, $merged);

            // 1. Update winner with merged snapshot.
            $winner->forceFill(array_merge(
                $merged,
                ['updated_at' => now()],
            ))->save();

            // 2. Re-point FK rows from loser → winner. Single bulk UPDATE
            //    per table — order-independent and dedup-safe (the unique
            //    index on external_identities would otherwise collide if a
            //    loser identity was a duplicate of a winner identity, but
            //    re-pointing the loser's row to the winner never violates
            //    that index because the contact_id is the only field changing).
            $loserIds = $losers->pluck('id')->all();
            $winnerId = (string) $winner->id;

            ExternalIdentity::query()
                ->withoutWorkspaceScope()
                ->whereIn('contact_id', $loserIds)
                ->update(['contact_id' => $winnerId]);

            ContactNote::query()
                ->withoutWorkspaceScope()
                ->whereIn('contact_id', $loserIds)
                ->update(['contact_id' => $winnerId]);

            Lead::query()
                ->withoutWorkspaceScope()
                ->whereIn('contact_id', $loserIds)
                ->update(['contact_id' => $winnerId]);

            Conversation::query()
                ->withoutWorkspaceScope()
                ->whereIn('contact_id', $loserIds)
                ->update(['contact_id' => $winnerId]);

            // timeline_activities.subject_id INTENTIONALLY NOT re-pointed
            // (spec 15 § C5: "we don't merge timeline rows, they stay
            // attributed to whoever created them"). The schema has no
            // FK on subject_id anyway.

            // 3. Hard-delete losers. contact_notes has cascadeOnDelete
            //    (already re-pointed above), so notes are safe. Identities
            //    and leads have nullOnDelete — they're safely re-pointed
            //    too. timeline_activities has no FK, so it stays.
            Contact::query()
                ->withoutWorkspaceScope()
                ->whereIn('id', $loserIds)
                ->delete();

            // 4. Audit row.
            AuditLog::create([
                'workspace_id' => $winner->workspace_id,
                'actor_id' => null, // SYSTEM action; controller can patch this
                'module' => 'crm',
                'action' => 'contacts.merged',
                'subject_type' => 'contact',
                'subject_id' => $winnerId,
                'metadata' => [
                    'winner_id' => $winnerId,
                    'loser_ids' => $loserIds,
                    'diffs' => $diffs,
                ],
            ]);

            return $winner->fresh();
        });
    }

    /**
     * Compute the merged-field snapshot from winner + losers. Pure
     * function — no DB writes.
     *
     * @param  Collection<int, Contact>  $losers
     * @return array<string, mixed> fields safe to assign to the winner
     */
    private function applyPolicy(Contact $winner, Collection $losers): array
    {
        // Track the highest-trust identity count we've seen so far. A
        // contact with more identities is "more trusted" — its full_name
        // and avatar_url win over a less-trusted peer's.
        $winnerIdentityCount = $winner->identities()->count();
        $winnerAvatarTrust = $winnerIdentityCount;
        $winnerNameTrust = $winnerIdentityCount;

        // full_name: prefer non-empty. If both non-empty, prefer the one
        // from the contact with more identities (more trusted source).
        $fullName = (string) ($winner->full_name ?? '');
        $avatarUrl = $winner->avatar_url;

        foreach ($losers as $loser) {
            $loserIdentityCount = $loser->identities()->count();

            $loserName = (string) ($loser->full_name ?? '');
            if ($fullName === '' && $loserName !== '') {
                $fullName = $loserName;
                $winnerNameTrust = $loserIdentityCount;
            } elseif ($fullName !== '' && $loserName !== '' && $loserIdentityCount > $winnerNameTrust) {
                // Loser has a fuller identity graph — its name wins.
                $fullName = $loserName;
                $winnerNameTrust = $loserIdentityCount;
            }

            $loserAvatar = $loser->avatar_url;
            if (empty($avatarUrl) && ! empty($loserAvatar)) {
                $avatarUrl = $loserAvatar;
                $winnerAvatarTrust = $loserIdentityCount;
            } elseif (! empty($avatarUrl) && ! empty($loserAvatar) && $loserIdentityCount > $winnerAvatarTrust) {
                $avatarUrl = $loserAvatar;
                $winnerAvatarTrust = $loserIdentityCount;
            }
        }

        // phone / email: schema can hold one value. If winner's is
        // empty, take loser's. If both non-empty and equal, no-op.
        // If both non-empty and differ, keep winner's and flag the
        // conflict in the diff for the audit log.
        $phone = $winner->phone;
        $phoneNormalized = $winner->phone_normalized;
        $email = $winner->email;

        foreach ($losers as $loser) {
            if (empty($phone) && ! empty($loser->phone)) {
                $phone = $loser->phone;
                $phoneNormalized = $loser->phone_normalized;
            }
            if (empty($email) && ! empty($loser->email)) {
                $email = $loser->email;
            }
        }

        // tags: union.
        $tags = array_values(array_unique(array_merge(
            $winner->tags ?? [],
            $losers->flatMap(fn (Contact $c) => $c->tags ?? [])->all(),
        )));

        // status: most permissive (ACTIVE > ARCHIVED > BLOCKED).
        $status = $winner->status;
        foreach ($losers as $loser) {
            if ($this->statusRank($loser->status) < $this->statusRank($status)) {
                $status = $loser->status;
            }
        }

        // owner_id: always keep winner's.
        $ownerId = $winner->owner_id;

        // last_inbound_at: max.
        $lastInboundAt = $winner->last_inbound_at;
        foreach ($losers as $loser) {
            if ($loser->last_inbound_at !== null) {
                if ($lastInboundAt === null || $loser->last_inbound_at->greaterThan($lastInboundAt)) {
                    $lastInboundAt = $loser->last_inbound_at;
                }
            }
        }

        // attributes: shallow merge, loser wins on conflict (most
        // recent input).
        $attributes = $winner->attributes ?? [];
        foreach ($losers as $loser) {
            $attributes = array_merge($attributes, $loser->attributes ?? []);
        }

        // consent fields: first-write-wins (a later ingest shouldn't
        // erase the original consent capture).
        $consentGivenAt = $winner->consent_given_at;
        $consentText = $winner->consent_text;
        $consentIp = $winner->consent_ip;
        $consentUserAgent = $winner->consent_user_agent;
        foreach ($losers as $loser) {
            if ($consentGivenAt === null && $loser->consent_given_at !== null) {
                $consentGivenAt = $loser->consent_given_at;
            }
            if (empty($consentText) && ! empty($loser->consent_text)) {
                $consentText = $loser->consent_text;
            }
            if (empty($consentIp) && ! empty($loser->consent_ip)) {
                $consentIp = $loser->consent_ip;
            }
            if (empty($consentUserAgent) && ! empty($loser->consent_user_agent)) {
                $consentUserAgent = $loser->consent_user_agent;
            }
        }

        // source_detail: first-write-wins (the campaign tag at the
        // original ingest is the more trusted one).
        $sourceDetail = $winner->source_detail;
        foreach ($losers as $loser) {
            if (empty($sourceDetail) && ! empty($loser->source_detail)) {
                $sourceDetail = $loser->source_detail;
                break;
            }
        }

        return [
            'full_name' => $fullName,
            'phone' => $phone,
            'phone_normalized' => $phoneNormalized,
            'email' => $email,
            'avatar_url' => $avatarUrl,
            'tags' => $tags,
            'status' => $status,
            'owner_id' => $ownerId,
            'last_inbound_at' => $lastInboundAt,
            'attributes' => $attributes,
            'consent_given_at' => $consentGivenAt,
            'consent_text' => $consentText,
            'consent_ip' => $consentIp,
            'consent_user_agent' => $consentUserAgent,
            'source_detail' => $sourceDetail,
        ];
    }

    /**
     * Return a per-field diff: { field => { winner, losers: [...] } }
     * so the audit log carries a faithful summary and the UI can render
     * side-by-side preview.
     *
     * @param  Collection<int, Contact>  $losers
     * @param  array<string, mixed>  $merged
     * @return array<string, array<string, mixed>>
     */
    private function diffs(Contact $winner, Collection $losers, array $merged): array
    {
        $diffs = [];
        $winnerValues = [
            'full_name' => $winner->full_name,
            'phone' => $winner->phone,
            'email' => $winner->email,
            'avatar_url' => $winner->avatar_url,
            'tags' => $winner->tags ?? [],
            'status' => $winner->status,
            'last_inbound_at' => $winner->last_inbound_at?->toIso8601String(),
            'attributes' => $winner->attributes ?? [],
            'source_detail' => $winner->source_detail,
        ];
        $mergedValues = [
            'full_name' => $merged['full_name'],
            'phone' => $merged['phone'],
            'email' => $merged['email'],
            'avatar_url' => $merged['avatar_url'],
            'tags' => $merged['tags'],
            'status' => $merged['status'],
            'last_inbound_at' => $merged['last_inbound_at']?->toIso8601String(),
            'attributes' => $merged['attributes'],
            'source_detail' => $merged['source_detail'],
        ];

        foreach ($winnerValues as $field => $winnerVal) {
            $mergedVal = $mergedValues[$field] ?? null;
            $loserVals = $losers->map(fn (Contact $c) => [
                'id' => $c->id,
                'name' => $c->full_name,
                'value' => $this->normalizeDiffValue($c->{$field === 'attributes' ? 'attributes' : $field}),
            ])->all();

            if ($this->differs($winnerVal, $mergedVal) || $losers->contains(fn (Contact $c) => $this->differs($winnerVal, $c->{$field}))) {
                $diffs[$field] = [
                    'winner' => $this->normalizeDiffValue($winnerVal),
                    'losers' => $loserVals,
                    'merged' => $this->normalizeDiffValue($mergedVal),
                ];
            }
        }

        return $diffs;
    }

    private function normalizeDiffValue(mixed $value): mixed
    {
        if ($value instanceof \DateTimeInterface) {
            return $value->toIso8601String();
        }

        return $value;
    }

    private function differs(mixed $a, mixed $b): bool
    {
        if ($a instanceof \DateTimeInterface && $b instanceof \DateTimeInterface) {
            return $a->ne($b);
        }
        if (is_array($a) && is_array($b)) {
            return $a != $b;
        }

        return $a !== $b;
    }

    private function statusRank(string $status): int
    {
        $idx = array_search($status, self::STATUS_PERMISSIVE, true);

        return $idx === false ? PHP_INT_MAX : $idx;
    }
}
